server:
  port: 8020

eureka:
  client:
    service-url:
      #链接注册中心集群
       defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: consumer-web-8020                #定义微服务的名称,多个服务id必须不同
    prefer-ip-address: true                        #是否显示IP和端口

spring:
  application:    #定义服务名称
    name: consumer-web


feign:
  hystrix:
    enabled: true    #开启断路器机制